package org.mc.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.mc.adapters.binance.BinanceInstrumentSource;
import org.mc.adapters.binance.BinanceMarketDataSource;
import org.mc.adapters.bybit.BybitInstrumentSource;
import org.mc.adapters.bybit.BybitMarketDataSource;
import org.mc.services.SpotVsFutureArbTradeService;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.Timer;
import java.util.TimerTask;

public class ArbTradeView {
    private JTable table;
    private JPanel panel;
    private JSpinner minDaysToExpirySpinner;

    SpotVsFutureArbTradeService arbTradeService = new SpotVsFutureArbTradeService(
            new BinanceMarketDataSource(new BinanceInstrumentSource()),
            new BybitMarketDataSource(new BybitInstrumentSource()));

    ArbViewerTableModel tableModel = new ArbViewerTableModel();

    public static void main(String[] args) throws Exception {
//        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

//        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
//        defaults.putIfAbsent("Table.alternateRowColor", new Color(245, 245, 255));

        new ArbTradeView().init();
    }

    private void init() {
        table.setModel(tableModel);
        tableModel.initColumns(table);

        minDaysToExpirySpinner.setValue(5);

        JFrame frame = new JFrame("ArbTradeView");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.pack();
        frame.setSize(1200, 1200);
        frame.setVisible(true);

        var timer = new Timer(true);

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                updateTableData();
            }
        }, 0, 3000);
    }

    private void updateTableData() {
        var minDaysToExpiry = (int) minDaysToExpirySpinner.getValue();

        var trades = arbTradeService.getSortedTrades(minDaysToExpiry);

        Object[][] data = trades.stream().map(t ->
                new Object[]{t.buyQuote().instrument(), t.buyQuote().exchange(), t.getBuyPrice(),
                        t.sellQuote().instrument(), t.sellQuote().exchange(), t.getSellPrice(),
                        t.daysToExpiry(), t.getFlatPremium() * 100, t.getAnnualisedPremium() * 100}).toArray(Object[][]::new);

        SwingUtilities.invokeLater(() -> {
            tableModel.setNumRows(0);

            for (int i = 0; i < data.length; i++) {
                tableModel.insertRow(i, data[i]);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        table = new JTable();
        table.setAutoCreateRowSorter(true);
        table.setIntercellSpacing(new Dimension(20, -1));
        table.setRowHeight(25);
        table.setRowSelectionAllowed(false);
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        scrollPane1.setViewportView(table);
        final JLabel label1 = new JLabel();
        label1.setText("Minimum days to expiry:");
        panel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        minDaysToExpirySpinner = new JSpinner();
        panel.add(minDaysToExpirySpinner, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(60, -1), null, 1, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel.add(spacer2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
